### ISSUE TITLE
[Spec Preview] Don't generate PDFs

### ISSUE THREAD

**Issue by seshrs** [eecs280staff/tutorials#129]
In other repos on which I have configured spec previews, I set the option `generate_pdfs: false` to reduce how many GitHub Actions minutes are consumed.

However, I just noticed that this repo's spec preview workflow does not set this option. To save GitHub Actions minutes, you'll want to add this option below `configure_github_pages: false` below line 37:
https://github.com/eecs280staff/tutorials/blob/2ba78387b3053740e85305f8cb885ab9f7631fd4/.github/workflows/spec_preview.yml#L30-L37

Documentation: https://github.com/seshrs/build-primer-spec-action#setting-up-github-pages-deployment

**Comment by seshrs** [comment]
Oh I just realized this is a public repo 😆  You have unlimited GH Actions minutes IIRC.

Feel free to close this if it doesn't matter to you :)

**Comment by awdeorio** [comment]
I don't see a compelling reason to optimize pdfs of the tutorials.  I'll take this suggestion.
