### ISSUE TITLE
Windows VSCode sanitizers instructions refer to CodeLLDB, which is specific to macOS

### ISSUE THREAD

**Issue by broad-well** [eecs280staff/tutorials#135]
** What **
[The Sanitizers section of the VSCode setup tutorial](https://eecs280staff.github.io/tutorials/setup_vscode.html#sanitizers) refers to a CodeLLDB extension setting for all operating systems, but according to the [Extensions](https://eecs280staff.github.io/tutorials/setup_vscode.html#macos-1) section of the same tutorial, CodeLLDB is only to be installed for macOS.

** Where **
Hyperlinked above.

** Current language **
> Open Settings on VSCode (macOS: Code > Settings > Settings, Windows: File > Preferences > Settings). Search for “lldb: show disassembly” (without the quotes) and set the option to never. (See [ASAN error shows assembly code](https://eecs280staff.github.io/tutorials/setup_vscode.html#asan-error-shows-assembly-code) for an explanation.)

** Proposed **
Make the CodeLLDB setting change explicitly specific to macOS only.

**Comment by amirkamil** [comment]
Confirmed that this is not relevant to Windows.
