### ISSUE TITLE
Move "Restart" section of IDE tutorials to end

### ISSUE THREAD

**Issue by jamesjuett** [eecs280staff/tutorials#146]
I've noticed a number of students are a bit confused by the "Restart" section at the beginning of the IDE tutorials.

Essentially, it's too easy to interpret "Restart" as "Start". Here's the VS Code tutorial as an example:
![image](https://github.com/eecs280staff/tutorials/assets/14828215/64f2175a-9b5e-42d7-bfef-7466a11c0eeb)

The language "to start clean" is potentially ambiguous, and students don't necessarily have the context to quickly grok the commands given.

I also feel the positioning of the "Restart" section at the very top of the tutorial is distracting and contributes to this misunderstanding. This isn't where I'd intuitively expect to find full instructions for how to start over.

Here's a possible approach that I think would help:
1. Move the "Restart section" to the end.
2. Clarify the language a bit. (e.g. "to start clean" -> something more plain)
3. (optional) Put a quick sentence at the start of the tutorial that says something like "If you'd like to restart this tutorial, see [LINK]"

**Comment by awdeorio** [comment]
I like this suggestion.  We probably don't even need to include a pointer at the beginning.  The only people using this are those who have followed to the end and can't get it working.
