### ISSUE TITLE
Consider Installing VS Code Extensions via VS Code UI

### ISSUE THREAD

**Issue by jamesjuett** [eecs280staff/tutorials#149]
At least on Windows, installing extensions via the CLI is tricky.

Part of the complication is that you get different behavior whether you use PowerShell vs. bash, and that the ordering you install extensions is more sensitive, because they'll go to the wrong place if you don't install the WSL-remote extension first. For example, see #148.

Additionally, you can't get a full list of installed extensions, since PowerShell or bash will only give you the extensions installed in either local Windows VS Code or in WSL VS Code.

On the other hand, installing via the UI seems more robust. Ordering doesn't seem to matter, and you can visually see both local and WSL extensions. Plus, the UI gives a warning with a prompt to "install extension in WSL" if you somehow end up with e.g. the C++ extension installed locally but not in WSL.

I don't think the same issue exists on Mac, but it may be worth changing it for consistency as well.

I'll also add that I think installing them via the UI is more intuitive for students, and has other benefits, like familiarizing students with the extensions panel where they can search for and install others in the future. (The CLI approach lacks this discoverability.)

**Comment by awdeorio** [comment]
I would be fine with this

**Comment by jamesjuett** [comment]
I'll cook up a PR for this.

**Comment by amirkamil** [comment]
Closed by #156.
