### ISSUE TITLE
VS Code Windows: --list-extensions mismatch

### ISSUE THREAD

**Issue by jamesjuett** [eecs280staff/tutorials#151]
https://github.com/eecs280staff/tutorials/blob/568798de2439c089438399c6e7db749011002a6b/docs/setup_vscode_wsl.md?plain=1#L67C7-L68C7

On my machine, the WSL remote extension isn't shown when these commands are run from a bash shell. I believe that's because it only shows the extensions installed in WSL, and the WSL-remote extension shouldn't be installed there, just locally on the Windows side.

**Comment by awdeorio** [comment]
If we go with #151, does this issue go away?

**Comment by jamesjuett** [comment]
> If we go with #149, does this issue go away?

Yeah, pretty much. The UI clearly shows a list of local extensions and a list of extensions in WSL.

**Comment by awdeorio** [comment]
Sounds like we should go with #149 and kill both issues with one change.

**Comment by jamesjuett** [comment]
Agreed, though I had concurrently fixed it in #153. Won't hurt to fix there for now, just in case I don't get to #149 before the end of the day.
