### ISSUE TITLE
WSL User Account Creation

### ISSUE THREAD

**Issue by jamesjuett** [eecs280staff/tutorials#165]
Students sometimes end up skipping the step in the WSL setup tutorial where they create a user account. They should be prompted when they open the Ubuntu terminal as directed by the setup tutorial, but it doesn't directly mention this process.

Calling this out explicitly might help. We can also suggest best practices, e.g. something like what's show [here](https://learn.microsoft.com/en-us/windows/wsl/setup/environment#set-up-your-linux-username-and-password). I wouldn't suggest linking to that page, though, since it has a bunch of irrelevant stuff. Maybe these points?
- choose a user name that is all lowercase characters (could be your uniqname)
- while typing your password, the characters aren't shown. that's fine
- you can just hit enter to skip the other things (e.g. "room number" lol)

Also add a "pitfall" that has them check they aren't root. If they are, we could just suggest uninstalling and reinstalling WSL (if they have just installed it). Or, if students already had a previous installation, we might be able to find a resource to tell them how to create a user account, give it privileges, and make it the default user (this process is a bit complicated).

**Comment by awdeorio** [comment]
I totally agree with this.  We could even have a pitfall call out after this step on that root-user check you suggested.  I see problems in EECS 485 from students who probably made this mistake all the way back in EECS 280.

CC @ohjuny

**Comment by ohjuny** [comment]
I will take a closer took on Saturday!
