### ISSUE TITLE
Command Line tutorial link placement

### ISSUE THREAD

**Issue by stevenbogaerts** [eecs280staff/tutorials#167]
I wonder if some students are skipping the Command Line tutorial because of how it's placed on the EECS 280 tutorials page. Under "Setup Tutorial", step 1 is "Command Line Tools". The first links are Windows and macOS. A student would rightly assume they only need to do one of those two. Therefore they may not think that *all* students should subsequently do the command line tutorial. Similarly, step 2 (C++ Dev Environment) likely only requires students to follow one of the three links. 

So, maybe we should split this off into 4 steps. 1) Command Line Setup (Windows and Mac sub-links. 2) Command Line Use (one link to the CLI tutorial), 3) C++ Dev Environment, and 4) C++ Compilation.

**Comment by awdeorio** [comment]
Seems reasonable to me
