### ISSUE TITLE
Specify Ubuntu Version in WSL Tutorial

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#185]
When students install WSL using `wsl --install`, they may get different versions depending on *when* they perform the install.  We could make sure students get the same version with `wsl --install -d Ubuntu-24.04`.

For example, at the time of this writing (late August 2024), Ubuntu 22.02 is at end-of-life.  Ubuntu 24.04 is available in the Microsoft App Store, and it's recommended by the Microsoft WSL installations instructions, *but it isn't yet the default* with `wsl --install`.  I expect that this could change sometime soon, possibly even in the middle of our busy beginning-of-term "install season".

See related discussion [here](https://github.com/eecs280staff/tutorials/issues/184#issuecomment-2307685222)

**Comment by jamesjuett** [comment]
Some more context on lifecycles: https://ubuntu.com/about/release-cycle

Standard support (i.e. free) for Ubuntu 22.04 is good through April 2027.

Ubuntu 24.04 is fairly new. Official release was a few months ago, with standard support (i.e. free) good through April 2029.

In terms of "end of life", we're buying them an extra two years with 24.04, but I don't think that's a game changer for our purposes.

I also found this blog posting which speaks to Microsoft's policy for setting the default "Ubuntu" in the store and (presumably) via `wsl --install`:
https://ubuntu.com/blog/wsl-ubuntu-2022-year-in-review

It says:

> The default Ubuntu application on the Microsoft Store always provides the latest LTS release of Ubuntu after the first point release (for example Ubuntu 22.04.1 LTS and later).

It appears that Ubuntu 24.04.1 will be out August 29:
https://discourse.ubuntu.com/t/noble-numbat-24-04-1-lts-point-release-status-tracking/46972

I don't know whether Microsoft will immediately make that the default. But it is cutting it fairly close.

**Comment by jamesjuett** [comment]
I went ahead and merged the related PR. It makes me a little nervous that 24.04 is fairly new, and less stable than a 24.04.1 would be. However, if MS decides to randomly update the Linux kernel in a way that aggravates #184 , we will be glad to have Ubuntu 24.04 and g++ 13 available.

Merging was also time sensitive, as we just published everything for eecs280 about an hour ago :).
