### ISSUE TITLE
WSL file access from Windows

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#34]
The current tutorials advise WSL users to put files in `/mnt/c/...` so that it's easier to access them from Windows.  We should instead recommend putting the files in the Linux home and using the recently-added [File Explorer Linux shortcut](https://devblogs.microsoft.com/commandline/access-linux-filesystems-in-windows-and-wsl-2/#accessing-these-files-with-file-explorer).

**Comment by jamesjuett** [comment]
Another thing I recommend students do is navigate using that shortcut to their home directory, e.g. `/home/jjuett` and then right click to select "pin to quick access". That makes it even easier to get to their Linux files.
