### ISSUE TITLE
EECS 281 Tutorial

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#36]
It would be a nice service to publish an EECS 281 setup tutorial that uses the EECS 280 tutorials.

**Comment by awdeorio** [comment]
CC @zjweiss Take a look at the #6 for a checklist of what's still needed.  If you're interested in contributing, perhaps you could help with:
- get opt starter code
- get opt work around on Visual Studio

**Comment by zjweiss** [comment]
I'm still waiting for access to the EECS 281 github repos, but I have updated the tutorial here with the getopt instructions. It can be seen in PR https://github.com/eecs280staff/tutorials/pull/38.

One caveat is that I was having a hard time installing jekyll, so the styling may be slightly off.

**Comment by seshrs** [comment]
> One caveat is that I was having a hard time installing jekyll

Hi @zjweiss! I’d be happy to help debug your local setup, and would appreciate any help in improving the setup steps. If you’d like, could you create a new “discussion” here to get started? https://github.com/eecs485staff/primer-spec/discussions/categories/q-a

**Comment by zjweiss** [comment]
Hi @seshrs, I was able to get it all up and running. It turns out, I had an older version of gem installed, and it couldn't find racc.

PR https://github.com/eecs280staff/tutorials/pull/38 should have the newly debugged MD file.
