### ISSUE TITLE
VS Code / WSL screenshot

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#48]
It would nice to add a screenshot to the VS Code tutorial to accompany this pitfall:

> **Pitfall:** If you accidentally open VS Code from Windows mode, select "Reopen Folder in WSL".

Maybe something sort of like [this](https://ljr.im/articles/visual-studio-code-debugging-home-assistant-wsl-version/c5_p1_%E6%89%93%E5%BC%80%E6%9C%AC%E5%9C%B0%E7%9B%AE%E5%BD%95%E5%86%8D%E7%94%A8WSL%E9%87%8D%E6%96%B0%E5%8A%A0%E8%BD%BD.png)

Pro-tip: commit an unannotated screenshot first so we can play with the annotations if needed.

**Comment by awdeorio** [comment]
Would you be willing to take this on @zjweiss?

**Comment by zjweiss** [comment]
Happy to take it on.

**Comment by zjweiss** [comment]
Implemented in [f39c615](https://github.com/eecs280staff/tutorials/pull/50/commits/f39c615790526378052dbee99a72a44ecffa4e60)
