### ISSUE TITLE
CLI Tutorial How to Start a Terminal

### ISSUE THREAD

**Issue by awdeorio** [eecs280staff/tutorials#73]
I've seen a common error that students running WSL to start a powershell.  Maybe make this more explicit in the CLI tutorial.  Perhaps with a screenshot.

**Comment by ohjuny** [comment]
I am not exactly sure what it means that "students running WSL to start a powershell". Could you please clarify the error and what screenshot could help?

**Comment by awdeorio** [comment]
At the beginning of the CLI tutorial, we tell students to open a terminal.  In English, we say that on Windows you should open an Ubuntu Terminal, not a Powershell.  I've seen a number of students mess it up.  Perhaps a screenshot of what the terminal looks like on both macOS and Windows.

**Comment by ohjuny** [comment]
Ah I see, I will get on this tonight!

**Comment by ohjuny** [comment]
@awdeorio I am trying to get some Windows screenshots, but I just found out today that the school computers do not come with wsl+ubuntu. Also, you cannot install it as students do not have admin access. And I could not find something about it on the [Windows Set Up tutorial](https://eecs280staff.github.io/tutorials/setup_wsl.html).

I was wondering if you knew of a way to set up on the school computers?

**Comment by awdeorio** [comment]
I think the best solution here would be to recruit somebody on the staff with a windows machine to help.  Remind me and we can get a volunteer at the staff meeting today.

**Comment by awdeorio** [comment]
Update: would this work? https://eecs280staff.github.io/tutorials/images/wsl030.png It's from [here](https://eecs280staff.github.io/tutorials/setup_wsl.html#install-windows-subsystem-for-linux-wsl)

**Comment by ohjuny** [comment]
Yes I think this will work! I will get on this once I get off the bus 😀
