### ISSUE TITLE
C++ Extension Pack

### ISSUE THREAD

**Issue by jamesjuett** [eecs280staff/tutorials#81]
Our current VS Code setup has students install `ms-vscode.cpptools-extension-pack`. As far as I'm aware it's not necessary, and it also includes some random things they don't need and shouldn't use, like the CMake extension.

**Comment by awdeorio** [comment]
AFAIK its needed to intellisense.  Please correct me if I'm wrong.

**Comment by jamesjuett** [comment]
The regular [C/C++ extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools), i.e. `ms-vscode.cpptools` includes Intellisense.

The [extension "pack"](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools-extension-pack) is a bundle that includes the regular C/C++ extension plus some other extensions:
- C/C++, i.e. `ms-vscode.cpptools`
- C/C++ Themes, i.e. `ms-vscode.cpptools-themes`
- CMake, i.e. `twxs.cmake`
- CMake Tools, i.e. `ms-vscode.cmake-tools`

**Comment by awdeorio** [comment]
Can confirm that this is correct.  Here's what I have:
```console
$ code --list-extensions
ms-vscode.cpptools
vadimcn.vscode-lldb
```

With the ms-vscode extension disabled, intellisense is gone.  With it enabled, I have intellisense.
