### ISSUE TITLE
VSCode Setup -- Add example launch.json configurations

### ISSUE THREAD

**Issue by fizzaahmed** [eecs280staff/tutorials#88]
**What**
Update VSCode setup to include example configurations for a launch.json file for WSL and MacOS users. These should be available to copy/paste by students.

**Where**
This change would be in tutorials/docs/setup_vscode.md, shown to students [here](https://eecs280staff.github.io/tutorials/setup_vscode.html#compile-and-run).

**Why**
In previous semesters, we had students create their launch.json file this way, and I've noticed it was much easier for them to understand, and caused less problems. This semester I've noticed many more setup questions in this area that would have been easily solved with a launch.json file available to copy from the tutorial. This would help students who are trying to get through the setup tutorial, and staff in office hours.

**Comment by awdeorio** [comment]
One of the problems with posting a `launch.json` is that VS Code defaults change.  Furthermore, the correct launch.json can be different on different machines with different setups.  It's tricky to get this right.

A second reason to not include a sample `launch.json` is that it makes students dependent on the tutorial.  Presently, all you need to do is click "create launch.json" and the defaults almost entirely correct.

At the same time, we want students to get this right.  Any other suggestions?  For example, would it be helpful to include a troubleshooting tip to delete you launch.json and try again?
