### ISSUE TITLE
GitHub Pro is free for students

### ISSUE THREAD

**Issue by ohjuny** [eecs280staff/tutorials#94]
I know that the GitHub version control tutorial is part of 485, but creating this issue as I do not have access to 485 page (but this enhancement is beneficial to 280 students too).

Just discovered that GitHub Pro is free for college students, and students can register using this link: https://education.github.com/pack

Thought it may be nice to have a line somewhere in the GitHub version control tutorial mentioning this.

**Comment by awdeorio** [comment]
Got it
